export const CREATE_USUARIO = "CREATE_USUARIO";
export const RETRIEVE_USUARIOS = "RETRIEVE_USUARIOS";
export const UPDATE_USUARIO = "UPDATE_USUARIO";
export const DELETE_USUARIO = "DELETE_USUARIO";
export const DELETE_ALL_USUARIOS = "DELETE_ALL_USUARIOS";